import canonicalLaneMathlib.AdmissibleClass
import ChemicalThermodynamicsCanonicalLaneLean.ChemicalPotential
import ChemicalThermodynamicsCanonicalLaneLean.PhaseEquilibrium
import ChemicalThermodynamicsCanonicalLaneLean.ReactionKinetics
import ChemicalThermodynamicsCanonicalLaneLean.ThermodynamicPotentials
import ChemicalThermodynamicsCanonicalLaneLean.EntropyProduction
import ChemicalThermodynamicsCanonicalLaneLean.BridgeLemmas
import ChemicalThermodynamicsCanonicalLaneLean.GateLemmas

namespace HautevilleHouse
namespace ChemicalThermodynamicsCanonicalLaneLean

def ConstrainedThermodynamicsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_thermodynamics_endgame (A : AdmissibleClass) :
    ConstrainedThermodynamicsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ChemicalThermodynamicsCanonicalLaneLean
end HautevilleHouse